<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoordonneesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('coordonnees')->insert([
            [
                'id' => 1,
                'numero_civique' => '123',
                'rue' => 'Rue Saint-Denis',
                'bureau' => 'A1',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 1,
                'site_internet' => 'https://example.com',
                'code_postal' => 'H2X 3K9',
                'region_administrative' => 'Montréal',
                'created_at' => '2024-09-18 10:00:00',
            ],
            [
                'id' => 2,
                'numero_civique' => '456',
                'rue' => 'Boulevard René-Lévesque',
                'bureau' => 'B2',
                'ville' => 'Québec',
                'fiche_fournisseur_id' => 2,
                'province' => 'Québec',
                'site_internet' => 'https://quebecweb.com',
                'code_postal' => 'G1R 2B3',
                'region_administrative' => 'Capitale-Nationale',
                'created_at' => '2024-09-18 11:00:00',
            ],
            [
                'id' => 3,
                'numero_civique' => '789',
                'rue' => 'Avenue Laurier',
                'fiche_fournisseur_id' => 3,
                'bureau' => 'C3',
                'ville' => 'Gatineau',
                'province' => 'Québec',
                'site_internet' => 'https://gatineau.ca',
                'code_postal' => 'J8T 4H5',
                'region_administrative' => 'Outaouais',
                'created_at' => '2024-09-18 12:00:00',
            ],
            [
                'id' => 4,
                'numero_civique' => '101',
                'rue' => 'Rue Sherbrooke',
                'bureau' => 'D4',
                'fiche_fournisseur_id' => 4,
                'ville' => 'Sherbrooke',
                'province' => 'Québec',
                'site_internet' => 'https://sherbrooke.ca',
                'code_postal' => 'J1H 3Z1',
                'region_administrative' => 'Estrie',
                'created_at' => '2024-09-18 13:00:00',
            ],
            [
                'id' => 5,
                'numero_civique' => '202',
                'rue' => 'Chemin Sainte-Foy',
                'bureau' => 'E5',
                'fiche_fournisseur_id' => 5,
                'ville' => 'Laval',
                'province' => 'Québec',
                'site_internet' => 'https://laval.ca',
                'code_postal' => 'H7V 3Z4',
                'region_administrative' => 'Laval',
                'created_at' => '2024-09-18 14:00:00',
            ],
            [
                'id' => 6,
                'numero_civique' => '345',
                'rue' => 'Rue Wellington',
                'bureau' => 'F1',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 6,
                'site_internet' => 'https://montrealservices.com',
                'code_postal' => 'H3C 1V8',
                'region_administrative' => 'Montréal',
                'created_at' => '2024-09-19 10:00:00',
            ],
            [
                'id' => 7,
                'numero_civique' => '789',
                'rue' => 'Boulevard de la Capitale',
                'bureau' => 'G2',
                'ville' => 'Québec',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 7,
                'site_internet' => 'https://capitalequebec.com',
                'code_postal' => 'G1A 1B1',
                'region_administrative' => 'Capitale-Nationale',
                'created_at' => '2024-09-19 11:00:00',
            ],
            [
                'id' => 8,
                'numero_civique' => '512',
                'rue' => 'Avenue du Parc',
                'bureau' => 'H3',
                'ville' => 'Gatineau',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 8,
                'site_internet' => 'https://gatineaupro.com',
                'code_postal' => 'J8P 4R5',
                'region_administrative' => 'Outaouais',
                'created_at' => '2024-09-19 12:00:00',
            ],
            [
                'id' => 9,
                'numero_civique' => '654',
                'rue' => 'Boulevard Taschereau',
                'bureau' => 'I4',
                'ville' => 'Sherbrooke',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 9,
                'site_internet' => 'https://taschereauqc.com',
                'code_postal' => 'J1H 4Z9',
                'region_administrative' => 'Estrie',
                'created_at' => '2024-09-19 13:00:00',
            ],
            [
                'id' => 10,
                'numero_civique' => '213',
                'rue' => 'Rue Saint-Joseph',
                'bureau' => 'J5',
                'ville' => 'Laval',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 10,
                'site_internet' => 'https://lavalentreprises.com',
                'code_postal' => 'H7V 4K3',
                'region_administrative' => 'Laval',
                'created_at' => '2024-09-19 14:00:00',
            ],
            [
                'id' => 11,
                'numero_civique' => '105',
                'rue' => 'Avenue des Pins',
                'bureau' => 'K6',
                'ville' => 'Longueuil',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 11,
                'site_internet' => 'https://longueuilservices.ca',
                'code_postal' => 'J4V 3S2',
                'region_administrative' => 'Montérégie',
                'created_at' => '2024-09-20 10:00:00',
            ],
            [
                'id' => 12,
                'numero_civique' => '276',
                'rue' => 'Rue Lafontaine',
                'bureau' => 'L7',
                'ville' => 'Trois-Rivières',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 12,
                'site_internet' => 'https://trservices.com',
                'code_postal' => 'G9A 5W4',
                'region_administrative' => 'Mauricie',
                'created_at' => '2024-09-20 11:00:00',
            ],
            [
                'id' => 13,
                'numero_civique' => '888',
                'rue' => 'Rue Sainte-Catherine',
                'bureau' => 'M8',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 13,
                'site_internet' => 'https://stecatherinemon.com',
                'code_postal' => 'H2L 2V4',
                'region_administrative' => 'Montréal',
                'created_at' => '2024-09-20 12:00:00',
            ],
            [
                'id' => 14,
                'numero_civique' => '160',
                'rue' => 'Boulevard Laurier',
                'bureau' => 'N9',
                'ville' => 'Québec',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 14,
                'site_internet' => 'https://laurierquebec.ca',
                'code_postal' => 'G1V 4T1',
                'region_administrative' => 'Capitale-Nationale',
                'created_at' => '2024-09-20 13:00:00',
            ],
            [
                'id' => 15,
                'numero_civique' => '999',
                'rue' => 'Chemin Chambly',
                'bureau' => 'O10',
                'ville' => 'Longueuil',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 15,
                'site_internet' => 'https://cheminchambly.com',
                'code_postal' => 'J4H 1R5',
                'region_administrative' => 'Montérégie',
                'created_at' => '2024-09-20 14:00:00',
            ],
            [
                'id' => 16,
                'numero_civique' => '201',
                'rue' => 'Avenue Mont-Royal',
                'bureau' => 'P11',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 16,
                'site_internet' => 'https://montroyalmon.com',
                'code_postal' => 'H2T 3H6',
                'region_administrative' => 'Montréal',
                'created_at' => '2024-09-21 10:00:00',
            ],
            [
                'id' => 17,
                'numero_civique' => '630',
                'rue' => 'Rue King Ouest',
                'bureau' => 'Q12',
                'ville' => 'Sherbrooke',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 17,
                'site_internet' => 'https://kingouestsherbrooke.ca',
                'code_postal' => 'J1J 2N9',
                'region_administrative' => 'Estrie',
                'created_at' => '2024-09-21 11:00:00',
            ],
            [
                'id' => 18,
                'numero_civique' => '456',
                'rue' => 'Boulevard Sainte-Foy',
                'bureau' => 'R13',
                'ville' => 'Laval',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 18,
                'site_internet' => 'https://lavalsaintefoy.com',
                'code_postal' => 'H7V 2T4',
                'region_administrative' => 'Laval',
                'created_at' => '2024-09-21 12:00:00',
            ],
            [
                'id' => 19,
                'numero_civique' => '700',
                'rue' => 'Rue de la Montagne',
                'bureau' => 'S14',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 19,
                'site_internet' => 'https://delamontagne.ca',
                'code_postal' => 'H3G 1Y5',
                'region_administrative' => 'Montréal',
                'created_at' => '2024-09-21 13:00:00',
            ],
            [
                'id' => 20,
                'numero_civique' => '555',
                'rue' => 'Boulevard Saint-Laurent',
                'bureau' => 'T15',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 20,
                'site_internet' => 'https://boulevardstlaurent.ca',
                'code_postal' => 'H2Y 1Z3',
                'region_administrative' => 'Montréal',
                'created_at' => '2024-09-22 10:00:00',
            ],
            [
                'id' => 21,
                'numero_civique' => '150',
                'rue' => 'Rue du Fleuve',
                'bureau' => 'U16',
                'ville' => 'Trois-Rivières',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 21,
                'site_internet' => 'https://fleuvetr.com',
                'code_postal' => 'G9B 6A1',
                'region_administrative' => 'Mauricie',
                'created_at' => '2024-09-22 11:00:00',
            ],
            [
                'id' => 22,
                'numero_civique' => '409',
                'rue' => 'Rue King Est',
                'bureau' => 'V17',
                'ville' => 'Sherbrooke',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 22,
                'site_internet' => 'https://kingestsherbrooke.ca',
                'code_postal' => 'J1G 3H4',
                'region_administrative' => 'Estrie',
                'created_at' => '2024-09-22 12:00:00',
            ],
            [
                'id' => 23,
                'numero_civique' => '600',
                'rue' => 'Avenue des Champs',
                'bureau' => 'W18',
                'ville' => 'Québec',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 23,
                'site_internet' => 'https://champsav.ca',
                'code_postal' => 'G1R 5X2',
                'region_administrative' => 'Capitale-Nationale',
                'created_at' => '2024-09-22 13:00:00',
            ],
            [
                'id' => 24,
                'numero_civique' => '450',
                'rue' => 'Rue du Musée',
                'bureau' => 'X19',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 24,
                'site_internet' => 'https://rudemusee.ca',
                'code_postal' => 'H3G 1B3',
                'region_administrative' => 'Montréal',
                'created_at' => '2024-09-22 14:00:00',
            ],
            [
                'id' => 25,
                'numero_civique' => '110',
                'rue' => 'Boulevard Charest',
                'bureau' => 'Y20',
                'ville' => 'Québec',
                'province' => 'Québec',
                'fiche_fournisseur_id' => 25,
                'site_internet' => 'https://charestbvd.ca',
                'code_postal' => 'G1N 2E7',
                'region_administrative' => 'Capitale-Nationale',
                'created_at' => '2024-09-23 10:00:00',
            ],
        ]);
    }
}
