<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FicheFournisseursTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('fiche_fournisseurs')->insert([
            [
                'neq' => '1145678901',  // Respect des règles: 11 suivi de 4-9 puis 7 chiffres
                'etat' => 'En attente',
                'nom_entreprise' => 'Construction ABC Inc.',
                'adresse_courriel' => 'contact@abcconstruction.com',
                'password' => bcrypt('Abc123!@'),  // Respect des règles du mot de passe
                'details_specifications' => 'Construction de bâtiments commerciaux et résidentiels',
                'date_changement_etat' => null,

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '2245678902',
                'etat' => 'En attente',
                'nom_entreprise' => 'Rénovation Xyz Ltée',
                'adresse_courriel' => 'info@renovxyz.ca',
                'password' => bcrypt('Xyz456@!'),  // Respect des règles du mot de passe
                'details_specifications' => 'Rénovation et agrandissement résidentiel',
                'date_changement_etat' => null,

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '3345678903',
                'etat' => 'En attente',
                'nom_entreprise' => 'Plomberie 123',
                'adresse_courriel' => 'support@plomberie123.com',
                'password' => bcrypt('Plomb789$#'),
                'details_specifications' => 'Services de plomberie résidentielle et commerciale',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '8845678904',
                'etat' => 'En attente',
                'nom_entreprise' => 'Électricité Pro',
                'adresse_courriel' => 'contact@electropro.com',
                'password' => bcrypt('ElecPro321@#'),  // Respect des règles du mot de passe
                'details_specifications' => 'Installation de systèmes électriques pour bâtiments industriels',
                'date_changement_etat' => null,

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '1145678905',
                'etat' => 'En attente',
                'nom_entreprise' => 'Excavation Max',
                'adresse_courriel' => 'info@excavationmax.ca',
                'password' => bcrypt('ExcaMax123$%'),  // Respect des règles du mot de passe
                'details_specifications' => 'Excavation et terrassement',
                'date_changement_etat' => null,

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '1145678910',
                'etat' => 'En attente',
                'nom_entreprise' => 'Peinture Excellence',
                'adresse_courriel' => 'contact@peinture-excellence.com',
                'password' => bcrypt('PaintExcel123@!'),
                'details_specifications' => 'Service de peinture intérieure et extérieure',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '2245678911',
                'etat' => 'En attente',
                'nom_entreprise' => 'Paysagement Vert',
                'adresse_courriel' => 'info@paysagementvert.ca',
                'password' => bcrypt('LandGreen123@#'),
                'details_specifications' => 'Paysagement et entretien d’espaces verts',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '3345678912',
                'etat' => 'En attente',
                'nom_entreprise' => 'Maçonnerie Pro',
                'adresse_courriel' => 'contact@maconneriepro.com',
                'password' => bcrypt('MasonryPro456$%'),
                'details_specifications' => 'Travaux de maçonnerie pour résidences et bâtiments commerciaux',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '8845678913',
                'etat' => 'En attente',
                'nom_entreprise' => 'Menuiserie Experts',
                'adresse_courriel' => 'support@menuiserie-experts.com',
                'password' => bcrypt('WoodWork789!@'),
                'details_specifications' => 'Conception et installation de meubles sur mesure',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '1145678914',
                'etat' => 'En attente',
                'nom_entreprise' => 'Toiture Plus',
                'adresse_courriel' => 'contact@toitureplus.com',
                'password' => bcrypt('RoofPlus321#@'),
                'details_specifications' => 'Installation et réparation de toitures',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '2245678915',
                'etat' => 'En attente',
                'nom_entreprise' => 'Isolation Optimale',
                'adresse_courriel' => 'info@isolationoptimale.com',
                'password' => bcrypt('InsulOpt123@#'),
                'details_specifications' => 'Services d’isolation pour bâtiments résidentiels',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '3345678916',
                'etat' => 'En attente',
                'nom_entreprise' => 'Fenêtres et Portes Inc.',
                'adresse_courriel' => 'contact@fenport.com',
                'password' => bcrypt('WindowsDoors123$%'),
                'details_specifications' => 'Fabrication et installation de portes et fenêtres',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '8845678917',
                'etat' => 'En attente',
                'nom_entreprise' => 'Climatisation Pro',
                'adresse_courriel' => 'support@climpro.com',
                'password' => bcrypt('CoolAir456@#'),
                'details_specifications' => 'Installation de systèmes de climatisation et de chauffage',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '1145678918',
                'etat' => 'En attente',
                'nom_entreprise' => 'Carrelage Décor',
                'adresse_courriel' => 'info@carrelagedecor.com',
                'password' => bcrypt('TileDecor321@!'),
                'details_specifications' => 'Installation de carrelage et de revêtements de sol',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '2245678919',
                'etat' => 'En attente',
                'nom_entreprise' => 'Plâtre Plus',
                'adresse_courriel' => 'contact@platreplus.com',
                'password' => bcrypt('PlasterPro789@%'),
                'details_specifications' => 'Travaux de plâtrage et de finition intérieure',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '3345678920',
                'etat' => 'En attente',
                'nom_entreprise' => 'Serrurerie Express',
                'adresse_courriel' => 'contact@serrurerie-express.com',
                'password' => bcrypt('LockExpress123@!'),
                'details_specifications' => 'Services de serrurerie et sécurité',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '8845678921',
                'etat' => 'En attente',
                'nom_entreprise' => 'Démo Déconstruction',
                'adresse_courriel' => 'info@demo-deconstruction.ca',
                'password' => bcrypt('Demo456@#'),
                'details_specifications' => 'Travaux de démolition et de déconstruction',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '1145678922',
                'etat' => 'En attente',
                'nom_entreprise' => 'Gestion ÉcoDéchets',
                'adresse_courriel' => 'contact@ecodechets.com',
                'password' => bcrypt('EcoWaste123@#'),
                'details_specifications' => 'Gestion et recyclage des déchets de construction',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '2245678923',
                'etat' => 'En attente',
                'nom_entreprise' => 'Clôtures SécuriPlus',
                'adresse_courriel' => 'support@cloturesecuriplus.com',
                'password' => bcrypt('FenceSecure321$#'),
                'details_specifications' => 'Installation de clôtures de sécurité',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '3345678924',
                'etat' => 'En attente',
                'nom_entreprise' => 'Nettoyage Propreté',
                'adresse_courriel' => 'contact@nettoyageproprete.com',
                'password' => bcrypt('CleanPro123@!'),
                'details_specifications' => 'Services de nettoyage commercial et industriel',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '8845678925',
                'etat' => 'En attente',
                'nom_entreprise' => 'Signalisation Routière Québec',
                'adresse_courriel' => 'info@signalisationquebec.ca',
                'password' => bcrypt('Signal321@#'),
                'details_specifications' => 'Pose de signalisation routière et sécurité',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '1145678926',
                'etat' => 'En attente',
                'nom_entreprise' => 'Échafaudages Sécurisés',
                'adresse_courriel' => 'support@echafaudagesecurises.com',
                'password' => bcrypt('Scaffold456$#'),
                'details_specifications' => 'Location et montage d’échafaudages',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '2245678927',
                'etat' => 'En attente',
                'nom_entreprise' => 'Vitrerie Clair',
                'adresse_courriel' => 'contact@vitrerieclair.com',
                'password' => bcrypt('GlassClear123!@'),
                'details_specifications' => 'Installation et réparation de vitres et miroirs',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '3345678928',
                'etat' => 'En attente',
                'nom_entreprise' => 'Revêtement Extérieur Inc.',
                'adresse_courriel' => 'info@revetementexterieur.com',
                'password' => bcrypt('Exterior123@%'),
                'details_specifications' => 'Installation de revêtements extérieurs pour bâtiments',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'neq' => '8845678929',
                'etat' => 'En attente',
                'nom_entreprise' => 'Infrastructures Québec',
                'adresse_courriel' => 'contact@infrastructuresquebec.com',
                'password' => bcrypt('InfraQuebec789@#'),
                'details_specifications' => 'Construction d’infrastructures publiques et privées',
                'date_changement_etat' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
